sudo: required
services:
  - docker

before_install:
  - docker build -t alexisdevgrp/docker-react -f Dockerfile.dev .

script:
  - docker run alexisdevgrp/docker-react npm run test -- --coverage